import math

UNIT_TESTS = [
    # Question 1
    {
        "question": "Q1",
        "function_name": "straight_line",
        "input": [1, 0, 1],
        "expected": 1,
        "feedback": "Plotting in Desmos can be useful for checking what the correct answer may be",
    },
    {
        "question": "Q1",
        "function_name": "parabolic_line",
        "input": [1, 2, 3, 4],
        "expected": 27,
        "feedback": "Plotting in Desmos can be useful for checking what the correct answer may be",
    },
    {
        "question": "Q1",
        "function_name": "cubic_line",
        "input": [1, 2, 3, 4, 5],
        "expected": 194,
        "feedback": "Plotting in Desmos can be useful for checking what the correct answer may be",
    },
    {
        "question": "Q1",
        "function_name": "general_polynomial",
        "input": [[-1, 0.5], 1],
        "expected": -0.5,
        "feedback": "Plotting in Desmos can be useful for checking what the correct answer may be",
    },
    # Question 2
    {
        "question": "Q2",
        "function_name": "encrypt_char",
        "input": ["a"],
        "expected": "a",
        "feedback": "'a' as a num is not divisible by anything with a remainder",
    },
    {
        "question": "Q2",
        "function_name": "encrypt_char",
        "input": ["b"],
        "expected": "p",
        "feedback": "'b' as a num is divisible by only 2",
    },
    {
        "question": "Q2",
        "function_name": "encrypt_char",
        "input": ["c"],
        "expected": "z",
        "feedback": "'c' as a num is divisible by only 3",
    },
    {
        "question": "Q2",
        "function_name": "encrypt_word",
        "input": ["foo"],
        "expected": "xll",
    },
    # Question 3
    {
        "question": "Q3",
        "function_name": "add",
        "input": [1, 5],
        "expected": 6,
        "feedback": "1 + 5 is 6",
    },
    {
        "question": "Q3",
        "function_name": "sub",
        "input": [10, 2],
        "expected": 8,
        "feedback": "10 - 2 is 8",
    },
    {
        "question": "Q3",
        "function_name": "mult",
        "input": [7, 6],
        "expected": 42,
        "feedback": "7 * 6 = 42",
    },
    {
        "question": "Q3",
        "function_name": "div",
        "input": [10, 2],
        "expected": 5,
        "feedback": "10/2 = 5",
    },
    {
        "question": "Q3",
        "function_name": "simple_calc",
        "input": ["1 + 5"],
        "expected": 6,
        "feedback": "1 + 5 is 6",
    },
    {
        "question": "Q3",
        "function_name": "simple_calc",
        "input": ["5 - 100"],
        "expected": 0,
        "feedback": "Read the question very carefully about how to handle negative numbers",
    },
    {
        "question": "Q3",
        "function_name": "simple_calc",
        "input": ["7 * 6"],
        "expected": 42,
        "feedback": "7 * 6 = 42",
    },
    # Question 4
    {
        "question": "Q4",
        "function_name": "word_count",
        "input": ["this is a sentence"],
        "expected": 4,
    },
    {
        "question": "Q4",
        "function_name": "vowel_words",
        "input": ["this is a sentence with alphanumeric characters exhibiting vowels"],
        "expected": 4,
    },
    {
        "question": "Q4",
        "function_name": "um_count",
        "input": ["this um! sentence contains um. a nervous um, student"],
        "expected": 3,
    },
    {
        "question": "Q4",
        "function_name": "num_breaths",
        "input": ["this sentence. Is punctual, effective and exhilerating!"],
        "expected": 3,
    },
    {
        "question": "Q4",
        "function_name": "most_common_word",
        "input": ["engg1003 teaches python engg1003 is fun"],
        "expected": ("engg1003", 2),
    },
    {
        "question": "Q4",
        "function_name": "most_common_word",
        "input": ["ENGG1003 teaches python, engg1003 makes Python fun!"],
        "expected": ("Tie!", -1),
    },
    # Question 5
    {
        "question": "Q5",
        "function_name": "dist_between_points",
        "input": [[0, 0], [1, 0]],
        "expected": 1,
    },
    {
        "question": "Q5",
        "function_name": "average_dist_from_bullseye",
        "input": [[[1, 0], [0, 1], [-1, 0], [0, -1]]],
        "expected": 1,
    },
    {
        "question": "Q5",
        "function_name": "compute_dart_spread",
        "input": [[[0, 0], [1, 0]]],
        "expected": 1,
    },
    {
        "question": "Q5",
        "function_name": "dart_score",
        "input": [[0, 1]],
        "expected": 10,
        "feedback": "Remember what the boundary should give",
    },
    {
        "question": "Q5",
        "function_name": "dart_score",
        "input": [[0.5, 0.5]],
        "expected": 10,
        "feedback": "Remember what the boundary should give",
    },
    {
        "question": "Q5",
        "function_name": "dart_score",
        "input": [[2, 0]],
        "expected": 5,
        "feedback": "Remember what the boundary should give",
    },
    {
        "question": "Q5",
        "function_name": "dart_score",
        "input": [[0.5 / math.sqrt(2), 0.5 / math.sqrt(2)]],
        "expected": 10,
    },
    {
        "question": "Q5",
        "function_name": "game_score",
        "input": [[[0.8, 0.1], [1.1, 0.1], [-0.8, 2.5], [2.8, -2.8]]],
        "expected": 17,
    },
    {
        "question": "Q5",
        "function_name": "game_score",
        "input": [[[0, 10], [-1.5, -4]]],
        "expected": 0,
    },
    {
        "question": "Q5",
        "function_name": "play_dart_game",
        "input": [[[0, 0]], [[0, 0.5]]],
        "expected": "We are all winners here!",
        "feedback": "Both players hit red circle, same score",
    },
    {
        "question": "Q5",
        "function_name": "play_dart_game",
        "input": [[[0, 0.5], [0, 1.5], [0, 2]], [[0, 1], [0, 2.1], [0, 3]]],
        "expected": "Player A has won!",
        "feedback": "Player A: 10+5+5=20, Player B: 10+2+2=14",
    },
]
